# Generated by Django 5.2.15 on 2026-07-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон клиента')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Код страны телефона')),
                ('marketing_opt_in', models.BooleanField(default=False, verbose_name='Согласие на маркетинг')),
                ('legacy_wp_customer_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Legacy MotoPress customer ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'indexes': [models.Index(fields=['email'], name='bookings_cu_email_bec9bd_idx'), models.Index(fields=['phone'], name='bookings_cu_phone_a48e0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Публичный номер брони')),
                ('cruise_date', models.DateField(verbose_name='Дата круиза')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('adults_count', models.PositiveIntegerField(default=1, verbose_name='Количество взрослых')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='Количество детей')),
                ('total_seats', models.PositiveIntegerField(default=1, verbose_name='Всего занятых мест')),
                ('adult_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за взрослого')),
                ('child_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ребенка')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_payment', 'Ожидает оплату'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('expired', 'Истекло удержание'), ('payment_failed', 'Ошибка оплаты'), ('refunded', 'Возврат')], default='pending_payment', max_length=32, verbose_name='Статус брони')),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда истекает удержание мест')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('source', models.CharField(default='web', help_text='web, admin, migration, wp-compat', max_length=32, verbose_name='Источник брони')),
                ('legacy_wp_booking_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Legacy MotoPress booking ID')),
                ('legacy_wp_reservation_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Legacy MotoPress reservation ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено/истекло')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cruises.cruise', verbose_name='Круиз')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cruise', 'cruise_date', 'status'], name='bookings_bo_cruise__2b6df0_idx'), models.Index(fields=['hold_expires_at'], name='bookings_bo_hold_ex_ab9602_idx'), models.Index(fields=['legacy_wp_booking_id'], name='bookings_bo_legacy__fa890f_idx')],
            },
        ),
    ]
