# Generated by Django 5.2.15 on 2026-07-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='brevo', max_length=32, verbose_name='Email провайдер')),
                ('template_code', models.CharField(max_length=80, verbose_name='Код шаблона')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('delivered', 'Доставлено'), ('bounced', 'Возврат/отказ')], default='queued', max_length=32, verbose_name='Статус отправки')),
                ('provider_message_id', models.CharField(blank=True, max_length=160, verbose_name='ID сообщения у провайдера')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка отправки')),
                ('payload_snapshot', models.JSONField(default=dict, verbose_name='Снимок payload без секретов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Email лог',
                'verbose_name_plural': 'Email логи',
                'indexes': [models.Index(fields=['booking', 'template_code', 'recipient'], name='notificatio_booking_882e72_idx'), models.Index(fields=['status'], name='notificatio_status_18a272_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='clicksend', max_length=32, verbose_name='SMS провайдер')),
                ('recipient', models.CharField(max_length=64, verbose_name='Получатель')),
                ('message', models.TextField(verbose_name='Текст SMS')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('delivered', 'Доставлено')], default='queued', max_length=32, verbose_name='Статус отправки')),
                ('provider_message_id', models.CharField(blank=True, max_length=160, verbose_name='ID сообщения у провайдера')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'SMS лог',
                'verbose_name_plural': 'SMS логи',
                'indexes': [models.Index(fields=['booking', 'recipient'], name='notificatio_booking_1e074e_idx'), models.Index(fields=['status'], name='notificatio_status_532cc1_idx')],
            },
        ),
    ]
