# Generated by Django 5.2.15 on 2026-07-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='telegram', max_length=32, verbose_name='Провайдер')),
                ('recipient', models.CharField(max_length=64, verbose_name='Chat ID')),
                ('message', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='queued', max_length=32, verbose_name='Статус отправки')),
                ('provider_message_id', models.CharField(blank=True, max_length=160, verbose_name='ID сообщения')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Telegram лог',
                'verbose_name_plural': 'Telegram логи',
                'indexes': [models.Index(fields=['booking', 'recipient'], name='notificatio_booking_b75b93_idx'), models.Index(fields=['status'], name='notificatio_status_a0a06f_idx')],
            },
        ),
    ]
