# Generated by Django 5.2.15 on 2026-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='en', max_length=5)),
                ('slug', models.SlugField(max_length=120)),
                ('wp_slug', models.SlugField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_class', models.CharField(blank=True, max_length=80)),
                ('meta_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['locale', 'slug'],
                'unique_together': {('locale', 'slug')},
            },
        ),
    ]
