# Generated by Django 5.2.15 on 2026-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_siteconfig_sitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Hero/cover URL, e.g. /media/wp/2026/05/photo.jpg', max_length=512),
        ),
    ]
