# Generated by Django 5.2.15 on 2026-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_blog_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterModelOptions(
            name='sitepage',
            options={'ordering': ['locale', 'slug'], 'verbose_name': 'Страница сайта', 'verbose_name_plural': 'Страницы сайта'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Legacy URL from WordPress import', max_length=512),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
