# Generated by Django 5.2.15 on 2026-07-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=8, verbose_name='HTTP метод')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Путь')),
                ('action', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Action / endpoint')),
                ('query_string', models.CharField(blank=True, max_length=500, verbose_name='Query')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP статус')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность, мс')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Session ID')),
                ('booking_public_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Booking public ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('request_summary', models.JSONField(default=dict, verbose_name='Запрос (без секретов)')),
                ('response_summary', models.JSONField(default=dict, verbose_name='Ответ (без секретов)')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'API лог',
                'verbose_name_plural': 'API логи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'status_code', 'created_at'], name='audit_apire_path_542bbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('last_step', models.CharField(blank=True, max_length=64, verbose_name='Последний шаг')),
                ('last_event', models.CharField(blank=True, max_length=64, verbose_name='Последнее событие')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Дошёл до подтверждения')),
                ('is_abandoned', models.BooleanField(default=False, verbose_name='Брошена')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to='bookings.booking', verbose_name='Связанная бронь')),
            ],
            options={
                'verbose_name': 'Сессия посетителя',
                'verbose_name_plural': 'Сессии посетителей',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=32, verbose_name='Категория')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Действие')),
                ('status', models.CharField(choices=[('started', 'Начато'), ('success', 'Успех'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='started', max_length=16, verbose_name='Статус')),
                ('entity_type', models.CharField(blank=True, max_length=32, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сущности')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Session ID')),
                ('details', models.JSONField(default=dict, verbose_name='Детали (без секретов)')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'action', 'created_at'], name='audit_opera_categor_3900a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='JourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип события')),
                ('step', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Шаг воронки')),
                ('cruise_code', models.CharField(blank=True, max_length=32, verbose_name='Код круиза')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_events', to='bookings.booking', verbose_name='Бронь')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='audit.visitorsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Событие воронки',
                'verbose_name_plural': 'События воронки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_journ_event_t_570ac3_idx'), models.Index(fields=['step', 'created_at'], name='audit_journ_step_1eb9c5_idx')],
            },
        ),
    ]
