# Generated by Django 5.2.15 on 2026-07-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Системный код: morning, sunset. Используется в API и frontend.', unique=True, verbose_name='Код круиза')),
                ('name', models.CharField(max_length=160, verbose_name='Название круиза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_adult_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена взрослого')),
                ('default_child_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена ребенка')),
                ('child_allowed', models.BooleanField(default=True, verbose_name='Дети разрешены')),
                ('default_capacity', models.PositiveIntegerField(default=30, verbose_name='Базовая вместимость')),
                ('default_duration_minutes', models.PositiveIntegerField(default=240, verbose_name='Длительность по умолчанию, минут')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для бронирования')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('legacy_wp_service_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Legacy MotoPress service ID')),
            ],
            options={
                'verbose_name': 'Круиз',
                'verbose_name_plural': 'Круизы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CruiseDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='Переопределение вместимости')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Дата закрыта для бронирования')),
                ('adult_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Переопределение цены взрослого')),
                ('child_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Переопределение цены ребенка')),
                ('note', models.TextField(blank=True, verbose_name='Заметка администратора')),
                ('legacy_wp_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Legacy WP override ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='cruises.cruise', verbose_name='Круиз')),
            ],
            options={
                'verbose_name': 'Исключение/переопределение даты',
                'verbose_name_plural': 'Исключения/переопределения дат',
                'ordering': ['date', 'cruise'],
                'indexes': [models.Index(fields=['date', 'is_closed'], name='cruises_cru_date_faa6af_idx')],
                'unique_together': {('cruise', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CruiseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=понедельник, 6=воскресенье', verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('timezone', models.CharField(default='Asia/Nicosia', max_length=64, verbose_name='Часовой пояс')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с даты')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до даты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('legacy_wp_schedule_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Legacy MotoPress schedule ID')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cruises.cruise', verbose_name='Круиз')),
            ],
            options={
                'verbose_name': 'Расписание круиза',
                'verbose_name_plural': 'Расписания круизов',
                'ordering': ['cruise', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['cruise', 'weekday', 'is_active'], name='cruises_cru_cruise__b6f59f_idx'), models.Index(fields=['legacy_wp_schedule_id'], name='cruises_cru_legacy__4072c6_idx')],
            },
        ),
    ]
