# Generated by Django 5.2.15 on 2026-07-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, verbose_name='Провайдер webhook')),
                ('event_id', models.CharField(max_length=160, verbose_name='ID события')),
                ('event_type', models.CharField(max_length=160, verbose_name='Тип события')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Подпись проверена')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processing_error', models.TextField(blank=True, verbose_name='Ошибка обработки')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload события')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан в')),
            ],
            options={
                'verbose_name': 'Webhook лог',
                'verbose_name_plural': 'Webhook логи',
                'indexes': [models.Index(fields=['provider', 'event_type', 'processed'], name='payments_we_provide_1c4352_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=32, verbose_name='Платежный провайдер')),
                ('status', models.CharField(choices=[('requires_payment_method', 'Нужен способ оплаты'), ('requires_action', 'Нужно действие клиента'), ('processing', 'В обработке'), ('succeeded', 'Успешно оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], default='requires_payment_method', max_length=64, verbose_name='Статус платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Stripe PaymentIntent ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Stripe Checkout Session ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=128, verbose_name='Stripe Charge ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128, verbose_name='Stripe Customer ID')),
                ('transaction_id', models.CharField(blank=True, max_length=128, verbose_name='Внешний transaction ID')),
                ('provider_client_secret', models.CharField(blank=True, help_text='Не показывать клиенту вне платежного flow.', max_length=255, verbose_name='Stripe client secret')),
                ('idempotency_key', models.CharField(max_length=160, unique=True, verbose_name='Ключ идемпотентности')),
                ('raw_provider_status', models.CharField(blank=True, max_length=128, verbose_name='Исходный статус провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'), models.Index(fields=['provider'], name='payments_pa_provide_502c98_idx')],
            },
        ),
    ]
